CREATE schema DogWalkers;
USE DogWalkers;

CREATE TABLE Person
(
  Email VARCHAR(100) NOT NULL,
  P_Name VARCHAR(100) NOT NULL,
  Phone_number VARCHAR(10) NOT NULL,
  City VARCHAR(100) NOT NULL,
  PRIMARY KEY (Email)
);

CREATE TABLE Species
(
  Type_ID INT NOT NULL,
  Dog_Type VARCHAR(100) NOT NULL,
  Average_Height INT NOT NULL, 
  Average_Weight INT NOT NULL, 
  PRIMARY KEY (Type_ID)
);

CREATE TABLE Dogs
(
  Dog_ID INT NOT NULL auto_increment,
  Dog_Name VARCHAR(100) NOT NULL,
  Dog_Gender VARCHAR(100) NOT NULL,
  Dog_Age INT NOT NULL,
  Type_ID INT NOT NULL,
  PRIMARY KEY (Dog_ID),
  FOREIGN KEY (Type_ID) REFERENCES Species(Type_ID)	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Dog_Owner
(
  Email VARCHAR(100) NOT NULL,
  Registration_Date DATE NOT NULL,
  PRIMARY KEY (Email),
  FOREIGN KEY (Email) REFERENCES Person(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Has_Dogs
(
  Email VARCHAR(100) NOT NULL,
  Dog_ID INT NOT NULL,
  PRIMARY KEY (Email,Dog_ID),
  FOREIGN KEY (Dog_ID) REFERENCES Dogs(Dog_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Email) REFERENCES Dog_Owner(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Regular_Dog_Owner
(
  Email VARCHAR(100) NOT NULL,
  Monthly_Comission INT NOT NULL,
  PRIMARY KEY (Email),
  FOREIGN KEY (Email) REFERENCES Dog_Owner(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Premium_Dog_Owner
(
  Email VARCHAR(100) NOT NULL,
  Yearly_Comission INT NOT NULL,
  Full_Address VARCHAR(100) NOT NULL,
  PRIMARY KEY (Email),
  FOREIGN KEY (Email) REFERENCES Dog_Owner(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Dog_Walker
(
  Email VARCHAR(100) NOT NULL,
  Day_Price INT NOT NULL,
  Max_DogsPerDay INT NOT NULL,
  PRIMARY KEY (Email),
  FOREIGN KEY (Email) REFERENCES Person(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Specific_Working_Days
(
  Email VARCHAR(100) NOT NULL,
  Day_of_Work INT NOT NULL,
  PRIMARY KEY (Email, Day_of_Work),
  FOREIGN KEY (Email) REFERENCES Dog_Walker(Email) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Takes_Only
(
  Email VARCHAR(100) NOT NULL,
  Type_ID INT NOT NULL,
  PRIMARY KEY (Email, Type_ID),
  FOREIGN KEY (Email) REFERENCES Dog_Walker(Email) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Type_ID) REFERENCES Species(Type_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Taking_Dogs
(
  Email VARCHAR(100) NOT NULL,
  Day_of_Work INT NOT NULL,
  Dog_ID INT NOT NULL,
  PRIMARY KEY (Email, Day_of_Work, Dog_ID),
  FOREIGN KEY (Email, Day_of_Work) REFERENCES Specific_Working_Days(Email, Day_of_Work) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Dog_ID) REFERENCES Dogs(Dog_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
